name: lib1d_md
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6,<3.10
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - numpy
  - scipy>=1.9.0,<=1.10.1
  - matplotlib
  - tqdm
  - joblib